import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Section/Header";
import Footer from "@/components/Section/Footer";
import { Inter } from "next/font/google";
import StoreProvider from "@/components/Provider/StoreProvider";
import AuthProvider from "@/components/Provider/AuthProvider";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Jio Cinema",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${inter.className} antialiased`}>
        <StoreProvider>
          <AuthProvider>
            <Header />
            <main className="mt-[72px]">{children}</main>
            <Footer />
            <Toaster />
          </AuthProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
