import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Section/Header";
import Footer from "@/components/Section/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Jio Cinema",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <main className="mt-[75px">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
